### PR TITLE
feat: set arbitrary service hostname via annotation

### LINKED ISSUE #14: Expose service with arbitrary hostname
I'd like to expose a LoadBalancer service (or ideally, NodePort) on `_my_service._tcp.local`, but underscores aren't allowed in k8s service names. Could this be supported via an optional annotation with the preferred name?

### PR DESCRIPTION
**Pull request by pl4nty**
Fixes #14

Tested with `ghcr.io/pl4nty/external-mdns`

### CODE REVIEW

**Comment by iamasmith** [comment]
It strikes me that if this were multi-value with a label like hostnames, possibly comma separated, then this would also offer a workaround for #21  as well.
I'll pull your branch, rework and test and offer it back to you to consider as an update to this PR if that sounds reasonable?

**Comment by iamasmith** [comment]
@pl4nty An additional point, this PR as it stands only covers Add and not Delete, Update (Deletes and then Adds).

This leaves the availability of the record in a caching MDNS resolver at the mercy of TTL to remain consistent. I'll look at this in the scope of my PR.

**Comment by iamasmith** [comment]
Alt PR here allowing multiple hostnames and the ability to selectively turn on the more global without-default option for a specific service https://github.com/blake/external-mdns/pull/22

**Comment by blake** [comment]
Hi @pl4nty, thanks for the contribution. I think this is a great addition.

@iamasmith's recent PR includes your work as well as some additional enhancements. Would you be opposed to me closing this PR in favor of #22?

**Comment by pl4nty** [comment]
Sounds good, I'm happy to build/test the replacement PR too

**Pull request closed without merging**
